trigger:
  branches:
    include:
      - main

pool:
  name: tfnjpool

variables:
  NODE_ENV: production
  APP_DIR: /var/www/nodeapp

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build || echo "No build step defined"
  displayName: 'Install dependencies and build'

- script: |
    sshpass -p 'YourSecurePassword123!' ssh -o StrictHostKeyChecking=no azureuser@4.213.2.225 \
      "sudo rm -rf $APP_DIR && sudo mkdir -p $APP_DIR"

    sshpass -p 'YourSecurePassword123!' scp -o StrictHostKeyChecking=no -r ./public/* \
      azureuser@4.213.2.225:$APP_DIR/
  displayName: 'Copy static files to VM'

- script: |
    sshpass -p 'YourSecurePassword123!' ssh -o StrictHostKeyChecking=no azureuser@4.213.2.225 \
      "echo 'server {
        listen 80;
        server_name _;
        location / {
            root $APP_DIR;
            index index.html index.htm;
        }
      }' | sudo tee /etc/nginx/sites-available/nodeapp > /dev/null && \
      sudo ln -sf /etc/nginx/sites-available/nodeapp /etc/nginx/sites-enabled/nodeapp && \
      sudo nginx -t && sudo systemctl restart nginx"
  displayName: 'Configure NGINX reverse proxy'
