trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Self-hosted agent pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build Node.js App'

- script: |
    pm2 stop all || true
    pm2 start app.js
  displayName: 'Deploy with PM2'
